//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/TankControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @TankControl: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TankControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TankControl"",
    ""maps"": [
        {
            ""name"": ""TankGame"",
            ""id"": ""3f90e3a9-036d-47b7-a6e2-017324fb12ff"",
            ""actions"": [
                {
                    ""name"": ""Moving"",
                    ""type"": ""Value"",
                    ""id"": ""ffcc4637-4375-48b6-9cf1-967cef2d2ac6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""344aca30-cdfa-444f-ae11-852ba094f42b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a45581f4-553c-48d7-93f6-416ff9fff451"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""db8d2272-8f3d-41e0-a345-964bbe63ac16"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""17760824-96c1-4930-846d-ee5fa33bb016"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""035d71fd-6873-4fcd-8f25-ad44e98ae436"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Moving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TankGame
        m_TankGame = asset.FindActionMap("TankGame", throwIfNotFound: true);
        m_TankGame_Moving = m_TankGame.FindAction("Moving", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TankGame
    private readonly InputActionMap m_TankGame;
    private List<ITankGameActions> m_TankGameActionsCallbackInterfaces = new List<ITankGameActions>();
    private readonly InputAction m_TankGame_Moving;
    public struct TankGameActions
    {
        private @TankControl m_Wrapper;
        public TankGameActions(@TankControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @Moving => m_Wrapper.m_TankGame_Moving;
        public InputActionMap Get() { return m_Wrapper.m_TankGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TankGameActions set) { return set.Get(); }
        public void AddCallbacks(ITankGameActions instance)
        {
            if (instance == null || m_Wrapper.m_TankGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TankGameActionsCallbackInterfaces.Add(instance);
            @Moving.started += instance.OnMoving;
            @Moving.performed += instance.OnMoving;
            @Moving.canceled += instance.OnMoving;
        }

        private void UnregisterCallbacks(ITankGameActions instance)
        {
            @Moving.started -= instance.OnMoving;
            @Moving.performed -= instance.OnMoving;
            @Moving.canceled -= instance.OnMoving;
        }

        public void RemoveCallbacks(ITankGameActions instance)
        {
            if (m_Wrapper.m_TankGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITankGameActions instance)
        {
            foreach (var item in m_Wrapper.m_TankGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TankGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TankGameActions @TankGame => new TankGameActions(this);
    public interface ITankGameActions
    {
        void OnMoving(InputAction.CallbackContext context);
    }
}
